const textPresets = {
  1: {
    fontSize: "3.875rem",
    fontFamily: "Martian Mono",
    fontWeight: 700,
    lineHeight: "120%",
    letterSpacing: "-2px",
  },
  "1Mobile": {
    fontSize: "2.375rem",
    fontFamily: "Martian Mono",
    fontWeight: 700,
    lineHeight: "120%",
    letterSpacing: "-2px",
  },
  2: {
    fontSize: "3.125rem",
    fontFamily: "Martian Mono",
    fontWeight: 600,
    lineHeight: "130%",
    letterSpacing: "-2px",
  },
  "2Mobile": {
    fontSize: "2.125rem",
    fontFamily: "Martian Mono",
    fontWeight: 600,
    lineHeight: "130%",
    letterSpacing: "-2px",
  },
  3: {
    fontSize: "2.125rem",
    fontFamily: "Martian Mono",
    fontWeight: 600,
    lineHeight: "130%",
    letterSpacing: "-1px",
  },
  "3Mobile": {
    fontSize: "1.5rem",
    fontFamily: "Martian Mono",
    fontWeight: 600,
    lineHeight: "110%",
    letterSpacing: "-1px",
  },
  4: {
    fontSize: "1.5rem",
    fontFamily: "Martian Mono",
    fontWeight: 600,
    lineHeight: "110%",
    letterSpacing: "-1px",
  },
  "4Regular": {
    fontSize: "1.5rem",
    fontFamily: "Martian Mono",
    fontWeight: 400,
    lineHeight: "120%",
    letterSpacing: "-1px",
  },
  5: {
    fontSize: "1.25rem",
    fontFamily: "Inter",
    fontWeight: 400,
    lineHeight: "140%",
    letterSpacing: "-0.5px",
  },
  "5SemiBold": {
    fontSize: "1.25rem",
    fontFamily: "Inter",
    fontWeight: 600,
    lineHeight: "140%",
    letterSpacing: "-0.5px",
  },
  6: {
    fontSize: "1.125rem",
    fontFamily: "Martian Mono",
    fontWeight: 600,
    lineHeight: "130%",
    letterSpacing: "-1px",
  },
  "6Mobile": {
    fontSize: "1rem",
    fontFamily: "Martian Mono",
    fontWeight: 600,
    lineHeight: "130%",
    letterSpacing: "-1px",
  },
  7: {
    fontSize: "0.875rem",
    fontFamily: "Martian Mono",
    fontWeight: 400,
    lineHeight: "120%",
    letterSpacing: "-1px",
  },
};

export default textPresets;
